---
language: ruby
rvm:
  - 2.4.1
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
before_install:
  - wget "https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz" -O geckodriver.tar.gz
  - sudo tar xfz geckodriver.tar.gz -C /usr/local/bin
  - which geckodriver
  - geckodriver --version
install:
  - bundle install
script:
  - cucumber
  - cucumber -f json > cucumber-results.json